In [2]:
import numpy as np

In [8]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [9]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
prem=np.transpose(a)

In [11]:
print(prem)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
prem.ravel()

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [28]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [26]:
ze=np.zeros((2,2))

In [27]:
print(ze)

[[0. 0.]
 [0. 0.]]


In [24]:
one=np.ones((5,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
np.random.random((4,3))

array([[0.25190196, 0.75275265, 0.40141705],
       [0.19608846, 0.93506122, 0.59629418],
       [0.53522282, 0.45532451, 0.32188338],
       [0.69799275, 0.23556653, 0.88736981]])